/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp_order;

import erp.database.DBUtil;
import erp.database.Database;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetails
     */
    private int permission;

    public MainApp(int perm) {
        
        initComponents();
        this.permission = perm;
        setLocationRelativeTo(null);
        setTitle("ERP Solutions");
        setResizable(false);
        if ((this.permission & 1) == 0) {
            mItemInventoryManagement.setVisible(false);
        }
        if ((this.permission & 2) == 0) {
            mItemProductManagement.setVisible(false);
        }
        if (((this.permission & 1) == 0) && ((this.permission & 2) == 0)) {
            mainManuInventory.setVisible(false);
        }
        if ((this.permission & 4) == 0) {
            mItemNewOrder.setVisible(false);
            mainManuOrderDetails.setVisible(false);
        }
        if ((this.permission & 8) == 0) {
            mItemRequisition.setVisible(false);
        }
        if ((this.permission & 16) == 0) {
            mItemIssue.setVisible(false);
        }
        if(((this.permission & 8) == 0)&&((this.permission & 16) == 0)){
            mainManuRawMaterial.setVisible(false);
        }
         if ((this.permission & 32) == 0) {
           mItemProductionUpdate.setVisible(false);
           mainManuProduction.setVisible(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mainManuInventory = new javax.swing.JMenu();
        mItemInventoryManagement = new javax.swing.JMenuItem();
        mItemProductManagement = new javax.swing.JMenuItem();
        mainManuOrderDetails = new javax.swing.JMenu();
        mItemNewOrder = new javax.swing.JMenuItem();
        mainManuRawMaterial = new javax.swing.JMenu();
        mItemRequisition = new javax.swing.JMenuItem();
        mItemIssue = new javax.swing.JMenuItem();
        mainManuProduction = new javax.swing.JMenu();
        mItemProductionUpdate = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        jMenu9.setText("jMenu9");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Welcome To ERP Software");

        jMenu1.setText("File");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Log Out");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        mainManuInventory.setText("Inventory");

        mItemInventoryManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mItemInventoryManagement.setText("Inventory Management");
        mItemInventoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemInventoryManagementActionPerformed(evt);
            }
        });
        mainManuInventory.add(mItemInventoryManagement);

        mItemProductManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemProductManagement.setText("Product Management");
        mItemProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemProductManagementActionPerformed(evt);
            }
        });
        mainManuInventory.add(mItemProductManagement);

        jMenuBar1.add(mainManuInventory);

        mainManuOrderDetails.setText("Order Details");

        mItemNewOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mItemNewOrder.setText("New Order");
        mItemNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNewOrderActionPerformed(evt);
            }
        });
        mainManuOrderDetails.add(mItemNewOrder);

        jMenuBar1.add(mainManuOrderDetails);

        mainManuRawMaterial.setText("Raw Material");

        mItemRequisition.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mItemRequisition.setText("Requisition");
        mItemRequisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRequisitionActionPerformed(evt);
            }
        });
        mainManuRawMaterial.add(mItemRequisition);

        mItemIssue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mItemIssue.setText("Issue");
        mItemIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemIssueActionPerformed(evt);
            }
        });
        mainManuRawMaterial.add(mItemIssue);

        jMenuBar1.add(mainManuRawMaterial);

        mainManuProduction.setText("Production");

        mItemProductionUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mItemProductionUpdate.setText("Production Update");
        mItemProductionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemProductionUpdateActionPerformed(evt);
            }
        });
        mainManuProduction.add(mItemProductionUpdate);

        jMenuBar1.add(mainManuProduction);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mItemInventoryManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemInventoryManagementActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    new AddInventory(Database.getInventoryData(), MainApp.this).setVisible(true);
                    
                    
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
    }//GEN-LAST:event_mItemInventoryManagementActionPerformed

    private void mItemNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNewOrderActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetails(MainApp.this).setVisible(true);
            }
        });
    }//GEN-LAST:event_mItemNewOrderActionPerformed

    private void mItemIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemIssueActionPerformed
        new RawMaterialIssue(this).setVisible(true);
    }//GEN-LAST:event_mItemIssueActionPerformed

    private void mItemRequisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRequisitionActionPerformed

        new RawMaterialRequisition(MainApp.this).setVisible(true);
    }//GEN-LAST:event_mItemRequisitionActionPerformed

    private void mItemProductionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemProductionUpdateActionPerformed
        new ProductionUpdate(this).setVisible(true);
    }//GEN-LAST:event_mItemProductionUpdateActionPerformed

    private void mItemProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemProductManagementActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductManagement(Database.getProductReqData(), MainApp.this).setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
    }//GEN-LAST:event_mItemProductManagementActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.dispose();        
        Login.getInstance().setVisible(true);
        Login.getInstance().clear();
    }//GEN-LAST:event_jMenuItem9ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mItemInventoryManagement;
    private javax.swing.JMenuItem mItemIssue;
    private javax.swing.JMenuItem mItemNewOrder;
    private javax.swing.JMenuItem mItemProductManagement;
    private javax.swing.JMenuItem mItemProductionUpdate;
    private javax.swing.JMenuItem mItemRequisition;
    private javax.swing.JMenu mainManuInventory;
    private javax.swing.JMenu mainManuOrderDetails;
    private javax.swing.JMenu mainManuProduction;
    private javax.swing.JMenu mainManuRawMaterial;
    // End of variables declaration//GEN-END:variables
}
